{
 "title": "Container Resource Usage",
 "tags": [
  "kubernetes",
  "pod",
  "memory",
  "cpu"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total, namespace)"
    }
   },
   { "name": "pod", "query": ".+" }
  ]
 },
 "panels": [
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", pod=~\"$pod\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage (millicore)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{image!=\"\", pod=~\"$pod\", namespace=~\"$namespace\"}[1m])) by (pod) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Network",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"$pod\", namespace=~\"$namespace\"}[2m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod=~\"$pod\", namespace=~\"$namespace\"}[2m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  }
 ]
}