apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: default
  labels:
    advertise: bgp
spec:
  advertisements:
  - advertisementType: Service
    service:
      addresses:
      - LoadBalancerIP
    selector:
      matchLabels:
        cilium-bgp-advertise: default
