data_dir: /vector-data-dir
api:
  enabled: true
  address: 0.0.0.0:8686
sources:
  kubernetes_logs:
    type: kubernetes_logs
  host_metrics:
    filesystem:
      devices:
        excludes: [binfmt_misc]
      filesystems:
        excludes: [binfmt_misc]
      mountpoints:
        excludes: ["*/proc/sys/fs/binfmt_misc"]
    type: host_metrics
  internal_metrics:
    type: internal_metrics
sinks:
  kubernetes_loki:
    type: "loki"
    inputs:
    - kubernetes_logs
    endpoint: http://loki-gateway.logging:80
    out_of_order_action: accept
    encoding:
      codec: text
    labels:
      job: "vector"
      source: "kubernetes_logs"
      stream: "s-{{ stream }}"
      pod_host: "h-{{ kubernetes.pod_node_name }}"
      pod_name: "p-{{ kubernetes.pod_name }}"
      pod_namespace: "ns-{{ kubernetes.pod_namespace }}"
      container_name: "c-{{ kubernetes.container_name }}"
      file: "f-{{ file }}"
