apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/component: compact
  name: thanos-compact
spec:
  schedule: "23 7 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: compact
        spec:
          restartPolicy: OnFailure
          containers:
          - args:
            - compact
            - --retention.resolution-raw=60d
            - --retention.resolution-5m=180d
            - --retention.resolution-1h=720d
            - --objstore.config=$(OBJSTORE_CONFIG)
            - --data-dir=/var/thanos/compactor
            env:
            - name: OBJSTORE_CONFIG
              valueFrom:
                secretKeyRef:
                  key: thanos.yaml
                  name: thanos-objstore-config
            image: thanos
            resources:
              requests:
                cpu: "2"
                memory: 4Gi
            name: thanos-compactor
            volumeMounts:
            - mountPath: /var/thanos/compactor
              name: data
              readOnly: false
          terminationGracePeriodSeconds: 120
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: thanos-compact-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: compact
  name: thanos-compact-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "truenas-iscsi-general"
  resources:
    requests:
      storage: 30Gi
