---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: chrome
        image: karakeep-chrome
        args:
        - --disable-gpu
        - --disable-dev-shm-usage
        - --hide-scrollbars
        - --disable-blink-features=AutomationControlled
        - --window-size=1440,900
