apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: envoy-gateway
spec:
  destinations:
  - namespace: "envoy-gateway-system"
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
  - group: admissionregistration.k8s.io
    kind: ValidatingAdmissionPolicy
  - group: admissionregistration.k8s.io
    kind: ValidatingAdmissionPolicyBinding
  - group: gateway.networking.k8s.io
    kind: GatewayClass
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
spec:
  project: envoy-gateway
  source:
    path: kubernetes/envoy-gateway
  destination:
    namespace: envoy-gateway-system
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
