apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: truenas
namespace: truenas
resources:
- namespace.yaml
- certificate
- metrics

images:
- name: tls-cert-sync
  newName: ghcr.io/yuha0/tls-cert-sync
  newTag: v1.0.0
