apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: museum
resources:
- sealed-secret-museum-keys.yaml
- sealed-secret-s3.yaml
- sealed-secret-smtp.yaml
- deployment.yaml
- service.yaml
- httproute.yaml
- servicemonitor.yaml
configMapGenerator:
- name: museum-config
  files:
  - museum.yaml
