---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: museum-s3
  namespace: ente
spec:
  encryptedData:
    ENTE_S3_B2_EU_CEN_KEY: AgDIWpjs6zzqJs3tz6LZu4tqIVzFGCn3urJ2CUTaLriy9yuNPUlymcRwLoi5im1/sdIFJQsmNi4vucz6pLz2Zn6IZ3fRG06USB+Hd+eq8jCktPi2ol9rGnUuXFZnUDXdao2aCSMmrOyHGpRw5j0OsbwM4DKZ9B63NShhzJnmvCVUTzoFDudfdrVzAw7M9Axj41/3PUF87GPGY9mj/mkx7y9OjAO3cPO1ed/jgJP+TSt9TkVvfmqb7S2w9wbgjFTPmXbGkQDHZVCDf/qb8rBpBIWknt8sO3jvGGxd3aDl3IBej7xnSwte/WG/qGjr5yBT3CW3A7EmO40L6yvgj+C7FTotbYYRME7iv+z1BgY2BAbBXP7zDERSMxrCyez867vVVMkG5UROji4c8W5+xs8cwK9zrbKybv45gQuwwWHv/Wh1djsJ9sa31262L8Sh3/L2NEyZ01jGhwgDPikUruh3C04QjPYTH3mHr3kHDx+Z+rY1eMWEYMJhpbT8NBkEkoV388ADsOXClfhWThGN3ylCEp1M2GKphxJmrnOOsHb8OzHJy/6as49dopezegxWrYIY1Vi2WmgzCTkmkBsbROLPv64SvMA4hNLE1m6fJF8cdxcbRAhPUCQpDsRMveGurxM/kui6pjfG//HdyChifzwB0BrJrV0PG7PDgSaYbqvZwpP6b097upJtIiI5WWCjG9Wo8J/YJEQGYsdga50q2Mk/DXW9NgEdorJlpDWAVwHoTiEqxA==
    ENTE_S3_B2_EU_CEN_SECRET: AgCKqa2FEn+qEMjfGlhuQEVjbV4uXJBfIvnGGcbIMZG5zyB98HqanbIa78PyeTgbwmCf6mN8J/7PVsI4zP1vkGJCUTSBx3mduUsjAhZw9ipPYCgaPfVyuhhN1fE5NX9ASLwjcjwhfTprgxWtFDodGjfX5Kn40DPZTXj4gwx/8xHOft1aSbbom5BppHdQA2RDDxCpt2iOOAs25uFHnUppmX3VMxYGsQBrcllLK28TyJP7y0Y2ArV8ss5/LC0fipkoWwyW8sAxopPEIDRM4r9vDpfiR990wCfv6/RYGqXRHIMLOLzdsyWIePb7i5+nfCFSK2IcRWLKLD/7GN+JUVtwD6rbTcDn/wsXqh5+iu/BTHgPnGUitr1JTpX/HKEpp+D+jIUtjRO6vjnhXDPiy5GHjM1aAQUYNe0Aui+VUfK4aIm4/WCyZWDoT0CWSJjk+8QdHHs5DmYnQUOWkNhqsAQt/X1jPIyy1/gwOadfCOqx5DUFK299/GUDCEjD8sa/84CcsiKr2xNtjOQ/HEjlr0zSVbhFXPUZa8lI8A0q/1HxzaRzlemviex3afxzxw358VaPBmwIx4vhtdAOSVupnsETDhUz0AjbGzrFf73OidjLUui1MpSRHm1N1wzN1Gy1lJzmLtsSCw6e3zOdf96QzD74qfujAaCTYN9eB/rV0QGSLw+xtSt4aDMIBhskLXu3hdXA8/1Giwl+78P6Cj09dyeJE4GkHkXBaxhxA9OFMRPUqBeHBA==
  template:
    metadata:
      name: museum-s3
      namespace: ente
    type: Opaque
