apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: museum
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: ente
      app.kubernetes.io/component: museum
