apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-agent
  annotations:
    access.yuha0.com/kubeconfig: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: llm-agent-token
  annotations:
    kubernetes.io/service-account.name: llm-agent
type: kubernetes.io/service-account-token
