apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nut-exporter
spec:
  template:
    spec:
      nodeSelector:
        nodepool.yuha0.com/usb: ups
      containers:
      - name: nut-client
        image: nut-client
        securityContext:
          privileged: true
        env:
        - name: NUT_CLIENT_DRIVER
          value: "usbhid-ups"
        - name: NUT_CLIENT_NAME
          value: "ups"
        lifecycle:
          preStop:
            exec:
              command: ["upsdrvctl", "stop"]
        livenessProbe:
          tcpSocket:
            port: 3493
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 6
        envFrom:
        - secretRef:
            name: nut-client-secrets
      - name: nut-exporter
        image: nut-exporter
        ports:
        - containerPort: 9199
        args:
        - --nut.vars_enable
        - ""
