---
apiVersion: v1
kind: Service
metadata:
  name: tls-cert-sync
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tls-cert-sync
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: tls-cert-sync
        image: tls-cert-sync
        args:
        - --type=truenas
        - --url=https://truenas.lab.yuha0.com
        - --cert-dir=/certs
        - --interval=3600
        env:
        - name: SYNC_TRUENAS_API_KEY
          valueFrom:
            secretKeyRef:
              name: truenas-api-key
              key: api-key
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
      volumes:
        - name: certs
          secret:
            secretName: truenas-tls-certificate
