{
 "title": "UPS Overview",
 "tags": [
  "hardware",
  "ups",
  "power"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ups",
    "label": "UPS",
    "query": {
     "query": "label_values(network_ups_tools_device_info,ups)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Device Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UPS Status",
   "type": "stat",
   "description": " * OL - On line (mains is present)\n * OB - On battery (mains is not present)\n * LB - Low battery\n * HB - High battery\n * RB - The battery needs to be replaced\n * CHRG - The battery is charging\n * DISCHRG - The battery is discharging (inverter is providing load power)\n * BYPASS - UPS bypass circuit is active -- no battery protection is available\n * CAL - UPS is currently performing runtime calibration (on battery)\n * OFF - UPS is offline and is not supplying power to the load\n * OVER - UPS is overloaded\n * TRIM - UPS is trimming incoming voltage (called \"buck\" in some hardware)\n * BOOST - UPS is boosting incoming voltage\n * FSD and SD - Forced Shutdown",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (flag) (network_ups_tools_ups_status{ups=\"$ups\"} == 1)",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Battery Runtime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Manufacturer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (mfr) (network_ups_tools_device_info{ups=\"$ups\"})",
     "legendFormat": "{{mfr}}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (model) (network_ups_tools_device_info{ups=\"$ups\"})",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Beeper Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(network_ups_tools_ups_beeper_status{ups=\"$ups\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Load Percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{ups=\"$ups\"}",
     "legendFormat": "Load Percentage"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{ups=\"$ups\"} * network_ups_tools_ups_realpower_nominal{ups=\"$ups\"} / 100",
     "legendFormat": "UPS Load"
    },
    {
     "expr": "network_ups_tools_ups_realpower_nominal{ups=\"$ups\"}",
     "legendFormat": "Max Capacity"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Battery Charged",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(network_ups_tools_input_voltage{ups=\"$ups\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(network_ups_tools_battery_voltage{ups=\"$ups\"})"
    }
   ]
  }
 ]
}