apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/name: access
resources:
- namespace.yaml
- roles
- serviceaccounts
- kubeconfig
images:
- name: kubectl
  newName: docker.io/alpine/kubectl
  newTag: "1.35.3"
