---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tls-cert-sync-user
  namespace: unifi
spec:
  encryptedData:
    SYNC_UNIFI_PASSWORD: AgB0QhRRrbBHj1i1VOINXBxbi7EaOY5SigiDsJc6pj/Fsyg8Hzecx1FWKmhhS9XC00OFZWncIKtoGvpPW3WNuqgBt6pzsOH3c6cxmNdwdn/vrKQY4y9Nq/6eiTLb3moy2qmtvmDJuI3bMwUReo6nZxfF2dQIOZr3sR6DkJRB1A8yvnw87ISsk6D6U1obFzslbnx3wmYWf7OK2u8P2p60Bb1zYA89lmAEcSEC5UenXm9xyzMt1XYLoa+1nMpEkPyjr+WzmTQclchmPqwUUQ4l04NLFz29HrhyNjvnl1G+3KcEKMf81P9T01v6XqkSk5Ks7yf4p4cBYR3kUQXmFIAYEUImi49vTMvYQ5hhO3kg4qjzomE/mlr++QlTKLIlsUar7mn7YQHLjSqYLB+5eVcxlFVJXIQiMc3kj/mlQR1WLDH2vPojYL+yOhaPcXjTePeCJ0GOjVkcWtk7YhqtJvz6HJ7Pf0zRIaf5yb9cNWr3PREg+q9GbRFLfTjCRdXTUg92SBone1rq8Hugo1dGhJbd/agguV7bDb3shoIVb0LnbeFhPxdO6kiztxDWOaxOCNeJ5AYIjF3PSbg3RDFrGYNcWCbnwVQJkj7eHkOEiJg/UOwf5AQOMIPMBORsbgHw9+0nI0BshVDuJXRKCjM+e6LZ/6Qp/1dYbN/VNUYgqiIgWP0nZ5C0INkev6Hw9thalhtlFDE279LNSNjUa+BhUIVod5yeT86x8A==
    SYNC_UNIFI_USERNAME: AgBsejpt1/aVcIaHCPe0vpmSpas8uUG7ueKM66Ivyx+ngTuRIoagD4txnApY8k5AsdKEfvTyc1dfy7HfRJu1YIVKkI85A4tSLWpo9geT7umc/glMe4Vo8KqNYvosI33EshxshjtwfG7NUbcUrCwG03kP++9DL/P0vA7MTHAwGbdu8YJuDa/Jgd/t1aiNzfdO8BU5PfHj+2hIwL4pB6d/JEs3ayjzgAygwhgOKhKbe00IYbK+Z7Lx5s41oHEqbFoSq4HtnwhqlHx0cPVyg+r8t2FwIF3+NSl0FD/PGvDuvMt5Njf5tshlIDd/Wt7lNB2LpIggyvnNVZ+nKVy0lO0ClSMQSSIHIRfsDq5gCjQEYSkSjl73x0/9TiCU7FW5yJxFQ3SIGhdfHBeT0LnBN6Lfb2rCAASX/ELmAZgTSnjkX5iU+pWeAqZQ6UJCQiuVKmoDW2WiJtiVzEZnPFbKy7d1UacOJ9QS3V1TFGNJZHoiZyTGzspPzQvX8Ri9Y3ipt5odHO2qWxmCU+A+6VnEjeOfyPXSUwLEpymdB/iGcuOWdGe3Fig2gFOysBPbhNDYgu8lblrNt5nqiBAJXwc6auUGh0l4V+5zgDm9NiRk0HPyAhn9qvZ4GisH7DbCY1eIO+xoZReZWW4GqFELBT4utBaT9vlCqnYdzl5V51nW0JBR5+vEXkgIPsG4HJs09CYGkYG64LG4W3gnp11psVICPNZp
  template:
    metadata:
      creationTimestamp: null
      name: tls-cert-sync-user
      namespace: unifi
    type: Opaque
