---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    AUTH_KEY: AgCuWqsEXam9lXRBe0UUj5IGibjm/SU3rGYINaz9MzJUck7mVILaDMP6L38OZa59CaRS1DYdpd4/1+gbVBEmxLvdCrWEkGWdXQ6wh7caCsniNOmYFuBTYnJG2lOVn9H0IwKxbDm1hnEy/0WQ3a5sKzjugGBIRTVa97GcARyWiEy2V7sSoJkanlXETFF+TREZPec1JbHWwN6zwdFXR9VEQ6cbGBozmZ/BG5/z0+ekVYqslJHCMkAowtXNL/FPnKlN48IybJUxIe+Qf9lEEL7GznUGtE5PJP+4cLHMk77OnMtYfa0tm+sQamY6GN1x8h3/nJUo0McNDiZVDNsCRSNuxVvpW4jEE4M/NnLmwmJV+U6mLymGHUUcEdAPM5Xcxl1o+TtjQZkj/SMZTsHLu0PgqTDex+bhtaA0uHHuYsX4uGVam0QpVGCI4aZDBozOVuNDZa9Isx6jVXzzhq7fLqxXMGBnenhCBhRuJ8W6fH2x3eUarkbkAY6oJTix+w3r2dhOrVjTwfwHCNkJcnbMa/4HZxEjSsUNHOn+4HTMAoCH+bgWFx1CR2TqNbCy/gKJniGgiVkORoBBmzO4mLkj3sVdHi9uCB7/SULvbsFy31Zvf//CjdiRBduKDtNSmKoHHQMFLXOIODI8uuREz/OacAqbcVOV09CQeLkpimBpxh0NvnPXTDAgzzs3XOFd8HMFUGxrnTkJnSiCL4bw3hxwN+ABYeR5hj64qu70YNtOBWrUqWvsEG1DG6a5s0nU1Bg4EF6x9l7gyq+PxUY96RbeYtNq
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-auth
      namespace: tailscale
    type: Opaque
