apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: unifi
namespace: unifi
resources:
- namespace.yaml
- networkpolicies.yaml
- unpoller
- logging
- backup
- certificate

images:
- name: geoipupdate
  newName: ghcr.io/maxmind/geoipupdate
  newTag: v7.1.1
- name: vector
  newName: docker.io/timberio/vector
  newTag: 0.55.0-distroless-libc
- name: unpoller
  newName: ghcr.io/unpoller/unpoller
  newTag: v2.39.0
- name: tls-cert-sync
  newName: ghcr.io/yuha0/tls-cert-sync
  newTag: v1.1.1
