apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubenav-cluster-viewer
subjects:
- kind: ServiceAccount
  name: kubenav
  namespace: access
roleRef:
  kind: ClusterRole
  name: access-cluster-viewer
  apiGroup: rbac.authorization.k8s.io
