apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubenav
  annotations:
    access.yuha0.com/kubeconfig: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: kubenav-token
  annotations:
    kubernetes.io/service-account.name: kubenav
type: kubernetes.io/service-account-token
