apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-helm
      control-plane: envoy-gateway
  endpoints:
  - port: metrics
    interval: 15s
