apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: access-debug
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/ephemeralcontainers
  verbs:
  - get
  - update
  - patch
